trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Deploy/*

variables:
  STORAGE_ACCOUNT:    "bjdterraform001"
  DEV_AKS_RG_NAME:    "DevSub02_K8SDev_RG"           
  PRD_AKS_RG_NAME:    "DevSub02_K8S01_RG"
  ACR_NAME:           "bjd145"
  CLIENT_ID:          "4e565daf-621d-48d3-b010-1208da519cbe"
  SUBSCRIPTION_ID:    "bfafbd89-a2a3-43a5-af72-fb4ef0c514c1"
  TENANT_ID:          "72f988bf-86f1-41af-91ab-2d7cd011db47"

stages:
- stage: Build
  jobs: 
  - job: 'Publish_Files'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: Deploy
        TargetFolder: '$(build.artifactstagingdirectory)/Deploy'
    - task: CopyFiles@2
      inputs:
        SourceFolder: Code
        TargetFolder: '$(build.artifactstagingdirectory)/Code'
    - task: PublishBuildArtifacts@1
   
- stage: DeployDevelopment
  jobs:
  - deployment: 'Build_AKS'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'AKSDev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(System.ArtifactsDirectory)/'
            displayName: Get Artifacts 

          - task: Bash@3
            displayName: Build Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/create_cluster.sh'
              arguments: '"$(DEV_AKS_RG_NAME)" "development" "$(access_key)" "$(client_secret)"'
              
          - task: Bash@3
            displayName: Config Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/config_cluster.sh'

- stage: DeployProduction
  jobs:
  - deployment: 'Build_AKS'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'AKS'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(System.ArtifactsDirectory)/'
            displayName: Get Artifacts 

          - task: Bash@3
            displayName: Build Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/create_cluster.sh'
              arguments: '"$(PRD_AKS_RG_NAME)" "production" "$(access_key)" "$(client_secret)"'

          - task: Bash@3
            displayName: Config Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/config_cluster.sh'