trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Deploy/*

variables:
  STORAGE_ACCOUNT:    ""
  DEV_AKS_RG_NAME:    ""    
  PRD_AKS_RG_NAME:    ""
  ACR_NAME:           ""
  CLIENT_ID:          ""
  SUBSCRIPTION_ID:    ""
  TENANT_ID:          ""

stages:
- stage: Build
  jobs: 
  - job: 'Publish_Files'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: Deploy
        TargetFolder: '$(build.artifactstagingdirectory)/Deploy'
    - task: CopyFiles@2
      inputs:
        SourceFolder: Code
        TargetFolder: '$(build.artifactstagingdirectory)/Code'
    - task: PublishBuildArtifacts@1
   
- stage: DeployDevelopment
  jobs:
  - deployment: 'Build_AKS'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'AKSDev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(System.ArtifactsDirectory)/'
            displayName: Get Artifacts 

          - task: Bash@3
            displayName: Build Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/create_cluster.sh'
              arguments: '"$(DEV_AKS_RG_NAME)" "development" "$(access_key)" "$(client_secret)"'
              
          - task: Bash@3
            displayName: Config Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/config_cluster.sh'

- stage: DeployProduction
  jobs:
  - deployment: 'Build_AKS'
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: 'AKS'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(System.ArtifactsDirectory)/'
            displayName: Get Artifacts 

          - task: Bash@3
            displayName: Build Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/create_cluster.sh'
              arguments: '"$(PRD_AKS_RG_NAME)" "production" "$(access_key)" "$(client_secret)"'

          - task: Bash@3
            displayName: Config Cluster
            inputs:
              filePath: '$(Agent.BuildDirectory)/drop/Deploy/config_cluster.sh'